.TH PNGSPLIT "1" "October 2020" "pngsplit 1.0" "User Commands"
.SH NAME
pngsplit \- manual page for pngsplit 1.0
.SH SYNOPSIS
.B pngsplit
.RI [ options ]
.I pngfile
.RI [ pngfile \ [...]]
.SH DESCRIPTION
pngsplit, version 1.0 of 31 October 2020, by Greg Roelofs.
.PP
Split a PNG, MNG or JNG file into individual, numbered chunks (filenames
"foo.png.0000.sig", "foo.png.0001.IHDR", etc.).
.PP
This software is licensed under the GNU General Public License.
There is NO warranty.
.SH OPTIONS
.TP
.B \-force
overwrite existing output files
.TP
.B \-verbose
print more status messages (synonym:
.BR \-noquiet )
.IP
.SH "SEE ALSO"
.BR pngcheck (1),
.BR png-fix-IDAT-windowsize (1)
